# Generated by Django 4.0.1 on 2022-04-02 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Stock', '0002_rename_nombre_stock_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('proveedor', models.CharField(max_length=100)),
                ('cuit', models.CharField(max_length=11)),
                ('tipo_comprobante1', models.CharField(max_length=4)),
                ('tipo_comprobante2', models.CharField(max_length=1)),
                ('numero_comprobante', models.CharField(max_length=13)),
                ('cantidad', models.CharField(max_length=20)),
                ('precio_unitario', models.CharField(max_length=20)),
                ('importe_neto', models.CharField(max_length=20)),
                ('iva', models.CharField(max_length=20)),
                ('importe_iva', models.CharField(max_length=20)),
                ('no_gravado', models.CharField(max_length=20)),
                ('percepciones', models.CharField(max_length=20)),
                ('importe_total', models.CharField(max_length=20)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producto_compras', to='Stock.stock')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidad_compras', to='Stock.stock')),
            ],
        ),
    ]
