# Generated by Django 4.0.1 on 2022-04-02 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Compras', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compras',
            old_name='iva',
            new_name='alicuota_iva',
        ),
        migrations.AlterField(
            model_name='compras',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
