# Generated by Django 4.0.1 on 2022-04-12 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Compras', '0002_rename_iva_compras_alicuota_iva_alter_compras_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='compras',
            name='importe_total_control',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
